// import './globals.css'
import 'bootstrap/dist/css/bootstrap.css';

import Header from "../../component/Header";

export const metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      
      
      
     

      <body>
        
        <Header/>
        
        {children}
      
      
     
      
      </body>
    
    </html>
  )
}
